// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.MaterialDesign
{
    /// <summary>
    /// GoKart icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class GoKart : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M18,10H15.53L14.38,8.28L15.8,7.33L14.7,5.67L10.2,8.67L11.3,10.33L12.73,9.38L13.88,11.12L13,12H10.2L5.83,5.45L4.17,6.55L5.87,9.11C3.04,9.65 1,12.12 1,15V17H3A3,3 0 0,0 6,20A3,3 0 0,0 9,17H15A3,3 0 0,0 18,20A3,3 0 0,0 21,17H23V15A5,5 0 0,0 18,10M6,18.5A1.5,1.5 0 0,1 4.5,17A1.5,1.5 0 0,1 6,15.5A1.5,1.5 0 0,1 7.5,17A1.5,1.5 0 0,1 6,18.5M18,18.5A1.5,1.5 0 0,1 16.5,17A1.5,1.5 0 0,1 18,15.5A1.5,1.5 0 0,1 19.5,17A1.5,1.5 0 0,1 18,18.5Z"" />");
            builder.CloseElement();
        }
    }
}
