// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.MaterialDesign
{
    /// <summary>
    /// MdClouds icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class MdClouds : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M19.19 12.07C19.69 11.54 20 10.82 20 10C20 8.3 18.7 6.84 17 6.84H14.2C14.2 4.17 12.03 2 9.36 2C7.31 2 5.56 3.28 4.85 5.08C2.72 5.14 1 6.89 1 9.04C1 11.22 2.78 13 4.96 13H8.1C8.04 13.33 8 13.66 8 14H7.5C5.57 14 4 15.57 4 17.5S5.57 21 7.5 21H18.5C21 21 23 19 23 16.5C23 14.26 21.34 12.41 19.19 12.07M18.5 19H7.5C6.67 19 6 18.33 6 17.5S6.67 16 7.5 16H10V14C10 12.07 11.57 10.5 13.5 10.5S17 12.07 17 14H18.5C19.88 14 21 15.12 21 16.5S19.88 19 18.5 19Z"" />");
            builder.CloseElement();
        }
    }
}
