// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FontAwesome6
{
    /// <summary>
    /// Fa6SolidVault icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class Fa6SolidVault : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 512 512");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<!--! Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2024 Fonticons, Inc. --><path d=""M64 0C28.7 0 0 28.7 0 64L0 416c0 35.3 28.7 64 64 64l16 0 16 32 64 0 16-32 224 0 16 32 64 0 16-32 16 0c35.3 0 64-28.7 64-64l0-352c0-35.3-28.7-64-64-64L64 0zM224 320a80 80 0 1 0 0-160 80 80 0 1 0 0 160zm0-240a160 160 0 1 1 0 320 160 160 0 1 1 0-320zM480 221.3L480 336c0 8.8-7.2 16-16 16s-16-7.2-16-16l0-114.7c-18.6-6.6-32-24.4-32-45.3c0-26.5 21.5-48 48-48s48 21.5 48 48c0 20.9-13.4 38.7-32 45.3z""/>");
            builder.CloseElement();
        }
    }
}
