// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FontAwesome6
{
    /// <summary>
    /// Fa6SolidCrutch icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class Fa6SolidCrutch : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 512 512");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<!--! Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2024 Fonticons, Inc. --><path d=""M297.4 9.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160c-12.5-12.5-32.8-12.5-45.3 0zm-96 144l-34.8 34.8c-12.9 12.9-21.9 29.2-25.8 47.1L116.8 342.9c-1.3 5.9-4.3 11.4-8.6 15.7L9.4 457.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l98.8-98.8c4.3-4.3 9.7-7.3 15.7-8.6l107.6-23.9c17.8-4 34.1-12.9 47.1-25.8l34.7-34.7c0 0 .1-.1 .1-.1s.1-.1 .1-.1l74.6-74.6-45.3-45.3L336 242.7 269.3 176l52.1-52.1L276.1 78.6l-74.7 74.7zM224 221.3L290.7 288l-12.2 12.2c-4.3 4.3-9.7 7.3-15.7 8.6l-76.7 17 17-76.7c1.3-5.9 4.3-11.4 8.6-15.7L224 221.3z""/>");
            builder.CloseElement();
        }
    }
}
