// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlBoardHeartRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlBoardHeartRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M21.5 5.56a3.25 3.25 0 0 0-3.25-3.06h-12A3.25 3.25 0 0 0 3 5.75v12.19A3.25 3.25 0 0 0 6.26 21h7.12l-1.46-1.5H6.25c-.91 0-1.66-.7-1.74-1.59l-.01-.16V9.5h7v2.67c.45-.41.96-.71 1.5-.9V4h5.25c.91 0 1.66.7 1.74 1.59l.01.16v5.28c.52.06 1.03.2 1.5.45V5.56ZM6.25 4h5.25v4h-7V5.75c0-.92.7-1.67 1.6-1.75h.15Zm15.73 9.06a3.7 3.7 0 0 1 0 5.11l-4.45 4.6a.74.74 0 0 1-1.06 0l-4.45-4.6a3.73 3.73 0 0 1 0-5.11 3.4 3.4 0 0 1 4.94 0l.04.04.04-.04a3.42 3.42 0 0 1 4.94 0Z""/>");
            builder.CloseElement();
        }
    }
}
