// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlCallEndFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlCallEndFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""m21.95 13-.2 1.03a1.92 1.92 0 0 1-2.12 1.52l-2.05-.2a2.16 2.16 0 0 1-1.87-1.56l-.64-2.36a8.1 8.1 0 0 0-6.23.18l-.39 2.21a1.9 1.9 0 0 1-1.7 1.55l-2.04.2a2.17 2.17 0 0 1-2.28-1.5l-.3-1.05a2.82 2.82 0 0 1 .71-2.85c1.78-1.73 4.75-2.6 8.9-2.6 4.17 0 7.23.86 9.2 2.59.82.73 1.2 1.8 1 2.83Z""/>");
            builder.CloseElement();
        }
    }
}
