// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlCircleHighlightRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlCircleHighlightRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""m10.56 3.62 3.16 3.16a.75.75 0 0 0 1.06-1.06l-2.2-2.2c.83.06 1.64.23 2.4.51l2.49 2.5c.29.29.75.3 1.05.01A8.5 8.5 0 0 1 6.55 18.51a.75.75 0 0 0-.02-1.04l-2.5-2.5a8.46 8.46 0 0 1-.51-2.39l2.2 2.2a.75.75 0 0 0 1.06-1.06l-3.16-3.16c.09-.5.22-1 .4-1.48l2.7 2.7a.75.75 0 0 0 1.06-1.06L4.7 7.64c.23-.38.5-.75.78-1.1l2.74 2.74a.75.75 0 0 0 1.06-1.06L6.54 5.48c.35-.28.71-.55 1.1-.78l3.08 3.08a.75.75 0 0 0 1.06-1.06l-2.7-2.7c.47-.18.97-.31 1.48-.4ZM12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z""/>");
            builder.CloseElement();
        }
    }
}
