// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlColumnTripleEditFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlColumnTripleEditFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M2 18.5A2.5 2.5 0 0 0 4.5 21h1A2.5 2.5 0 0 0 8 18.5v-13A2.5 2.5 0 0 0 5.5 3h-1A2.5 2.5 0 0 0 2 5.5v13Zm7 0a2.5 2.5 0 0 0 2.17 2.48l.35-1.4c.16-.65.5-1.24.97-1.72l2.51-2.5V5.5A2.5 2.5 0 0 0 12.5 3h-1A2.5 2.5 0 0 0 9 5.5v13ZM19.5 21h-.85L22 17.65v.85a2.5 2.5 0 0 1-2.5 2.5ZM22 5.5v5.76a3.29 3.29 0 0 0-3.6.7l-2.4 2.4V5.5A2.5 2.5 0 0 1 18.5 3h1A2.5 2.5 0 0 1 22 5.5Zm-2.9 7.17-5.9 5.9c-.35.35-.6.78-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46c.47-.12.9-.36 1.25-.7l5.9-5.9a2.29 2.29 0 0 0-3.23-3.24Z""/>");
            builder.CloseElement();
        }
    }
}
