// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlDataPieRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlDataPieRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M12.73 2.22a.75.75 0 0 1 .54-.22A9 9 0 0 1 22 10.73a.75.75 0 0 1-.75.77h-8a.75.75 0 0 1-.75-.75v-8c0-.2.08-.4.23-.53ZM14 3.57V10h6.43A7.5 7.5 0 0 0 14 3.57Zm-3 1.2a.75.75 0 0 0-.82-.75 9 9 0 1 0 9.78 9.8.75.75 0 0 0-.75-.82h-5.96C12.01 13 11 12 11 10.75V4.76Zm-7.5 8.21a7.5 7.5 0 0 1 6-7.35v5.12a3.75 3.75 0 0 0 3.75 3.75h5.1A7.5 7.5 0 0 1 3.5 12.98Z""/>");
            builder.CloseElement();
        }
    }
}
