// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlDiversityFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlDiversityFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M15.25 3C14.01 3 13 4 13 5.25v3.5C13 9.99 14 11 15.25 11h3.5C19.99 11 21 10 21 8.75v-3.5C21 4.01 20 3 18.75 3h-3.5Zm-6.8.9c-.6-1.2-2.3-1.2-2.9 0L3.18 8.6A1.64 1.64 0 0 0 4.63 11h4.74c1.22 0 2-1.3 1.45-2.39L8.45 3.9ZM3 17a4 4 0 1 1 8 0 4 4 0 0 1-8 0Zm13.38-4.26c.38-.22.86-.22 1.25 0l2.74 1.6c.39.21.63.63.63 1.07v3.18c0 .44-.24.86-.63 1.08l-2.75 1.59c-.38.22-.86.22-1.25 0l-2.74-1.6A1.25 1.25 0 0 1 13 18.6V15.4c0-.44.24-.86.63-1.08l2.74-1.59Z""/>");
            builder.CloseElement();
        }
    }
}
