// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlDocument100Filled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlDocument100Filled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M12 8V2H6a2 2 0 0 0-2 2v10.23a2 2 0 0 1 .86.97 3.5 3.5 0 0 1 5.64.5 3.5 3.5 0 0 1 6.5 1.8v2c0 .98-.4 1.86-1.05 2.5H18a2 2 0 0 0 2-2V10h-6a2 2 0 0 1-2-2Zm1.5 0V2.5l6 6H14a.5.5 0 0 1-.5-.5Zm-6 7A2.5 2.5 0 0 0 5 17.5v2a2.5 2.5 0 0 0 5 0v-2A2.5 2.5 0 0 0 7.5 15Zm-1 2.5a1 1 0 1 1 2 0v2a1 1 0 1 1-2 0v-2Zm4.5 0a2.5 2.5 0 0 1 5 0v2a2.5 2.5 0 0 1-5 0v-2Zm2.5-1a1 1 0 0 0-1 1v2a1 1 0 1 0 2 0v-2a1 1 0 0 0-1-1ZM4 15.94a1 1 0 0 0-.74-.95c-.31-.09-.8-.06-1.11.37-.32.44-.76.94-1.28 1.24a.75.75 0 0 0 .76 1.3c.32-.2.61-.43.87-.67v4.02a.75.75 0 0 0 1.5 0v-5.31Z""/>");
            builder.CloseElement();
        }
    }
}
