// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlDocumentMultiplePercentFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlDocumentMultiplePercentFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M6.5 12a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11Zm10.87 8.5c-.31.88-1.15 1.5-2.13 1.5H11.2c.42-.44.79-.95 1.08-1.5h5.1ZM9 17.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Zm.33-2.83a.5.5 0 0 0-.7 0l-4.96 4.95a.5.5 0 0 0 .71.7l4.95-4.94a.5.5 0 0 0 0-.7ZM9 18.5a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1ZM13 2v4.75C13 7.99 14 9 15.25 9H20v8.25c0 1.24-1 2.25-2.25 2.25h-5.06A6.5 6.5 0 0 0 6.5 11V4.25C6.5 3.01 7.5 2 8.75 2H13ZM4 14.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Zm0 1a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1Zm1.5-4.42c-.52.08-1.03.22-1.5.42V6.75c0-.98.63-1.81 1.5-2.12v6.45Zm14-3.58h-4.25a.75.75 0 0 1-.75-.75V2.5l5 5Z""/>");
            builder.CloseElement();
        }
    }
}
