// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlEyedropperOffFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlEyedropperOffFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""m8.94 10-4.78 4.78c-.42.42-.66 1-.66 1.6v.68L2.22 19.4c-.84 1.53.84 3.2 2.38 2.37l2.34-1.28h.69c.6 0 1.17-.24 1.6-.66L14 15.06l6.72 6.72a.75.75 0 0 0 1.06-1.06L3.28 2.22a.75.75 0 0 0-1.06 1.06L8.94 10Zm4 4-4.78 4.78a.75.75 0 0 1-.53.22h-.88a.75.75 0 0 0-.36.1l-2.51 1.36a.23.23 0 0 1-.16.04.26.26 0 0 1-.14-.08.26.26 0 0 1-.07-.14c-.01-.03-.01-.09.03-.16l1.37-2.51c.06-.11.1-.23.1-.36v-.88c0-.2.07-.39.21-.53L10 11.06 12.94 14Zm5.55-.93c-.5.5-1.2.63-1.82.42l-6.16-6.16a1.75 1.75 0 0 1 .42-1.82l.58-.58c.69-.69 1.8-.69 2.48 0l.01.01 1.97-1.97a3.58 3.58 0 0 1 5.06 5.06L19.06 10l.01.01c.69.69.69 1.8 0 2.48l-.58.58Z""/>");
            builder.CloseElement();
        }
    }
}
