// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlLeafTwoRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlLeafTwoRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M2 4.7V9a6 6 0 0 0 6.3 6c.26.88.69 1.69 1.25 2.39l-2.33 2.33a.75.75 0 0 0 1.06 1.06l2.33-2.33A7 7 0 0 0 22 13V7.75C22 6.78 21.22 6 20.25 6H15c-.58 0-1.15.07-1.69.2A6 6 0 0 0 8.01 3H3.7C2.77 3 2 3.76 2 4.7Zm9.68 12.68 4.1-4.1a.75.75 0 0 0-1.06-1.06l-4.1 4.1A5.5 5.5 0 0 1 15 7.5h5.25c.14 0 .25.1.25.25V13a5.5 5.5 0 0 1-8.82 4.38ZM8 4.5c1.66 0 3.1.9 3.89 2.23a7.03 7.03 0 0 0-2.71 2.39l-1.9-1.9a.75.75 0 0 0-1.06 1.06l2.24 2.24a6.98 6.98 0 0 0-.44 2.98H8A4.5 4.5 0 0 1 3.5 9V4.7c0-.1.1-.2.2-.2H8Z""/>");
            builder.CloseElement();
        }
    }
}
