// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlMicRecordRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlMicRecordRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M11 17.5c0 1.1.27 2.13.75 3.03v.72a.75.75 0 0 1-1.5.1v-2.37A6.75 6.75 0 0 1 4 12.48v-.73a.75.75 0 0 1 1.5-.1v.6a5.25 5.25 0 0 0 5.03 5.25H11ZM15 6v5.5a6.5 6.5 0 0 0-1.53.9c.02-.13.03-.26.03-.4V6a2.5 2.5 0 0 0-5 0v6a2.5 2.5 0 0 0 3.3 2.37c-.28.5-.49 1.05-.63 1.63H11a4 4 0 0 1-4-4V6a4 4 0 1 1 8 0Zm5 11.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm3 0a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0Zm-9.5 0a4 4 0 1 0 8 0 4 4 0 0 0-8 0Z""/>");
            builder.CloseElement();
        }
    }
}
