// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlPeopleQueueFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlPeopleQueueFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M10.5 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-5.75 4C3.78 10 3 10.78 3 11.75v4.75a4.5 4.5 0 1 0 9 0v-4.75c0-.97-.78-1.75-1.75-1.75h-5.5Zm6.11 10.85A5.5 5.5 0 0 0 13 16.5v-4.75c0-.66-.24-1.27-.63-1.75h2.38c.97 0 1.75.78 1.75 1.75v4.75a4.5 4.5 0 0 1-5.64 4.35ZM11.5 6c0 1-.37 1.91-.97 2.61a3 3 0 1 0 0-5.23c.6.7.97 1.62.97 2.62Zm3.86 14.85a5.5 5.5 0 0 0 2.14-4.35v-4.75c0-.66-.24-1.27-.63-1.75h2.38c.97 0 1.75.78 1.75 1.75v4.75a4.5 4.5 0 0 1-5.64 4.35ZM16 6c0 1-.37 1.91-.97 2.61a3 3 0 1 0 0-5.23c.6.7.97 1.62.97 2.62Z""/>");
            builder.CloseElement();
        }
    }
}
