// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlPhoneVibrateFilled icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlPhoneVibrateFilled : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M15.75 2C16.99 2 18 3 18 4.25v15.5c0 1.24-1 2.25-2.25 2.25h-7.5C7 22 6 21 6 19.75V4.25C6 3.01 7 2 8.25 2h7.5Zm-2.5 16h-2.5a.75.75 0 0 0-.1 1.5h2.6a.75.75 0 0 0 0-1.5Zm6.88-10.43a1 1 0 0 1 1.25.45l.05.1L22 9.6a3 3 0 0 1-.27 2.74l-.12.17-.15.2a1 1 0 0 0-.17.85l.04.12.59 1.46a1 1 0 0 1-1.81.85l-.05-.1-.58-1.47a3 3 0 0 1 .26-2.74l.12-.17.15-.2a1 1 0 0 0 .17-.85l-.04-.12-.58-1.46a1 1 0 0 1 .56-1.3Zm-17.5 0a1 1 0 0 1 1.25.45l.05.1.58 1.47a3 3 0 0 1-.27 2.74l-.12.17-.15.2a1 1 0 0 0-.17.85l.04.12.59 1.46a1 1 0 0 1-1.81.85l-.05-.1L2 14.4a3 3 0 0 1 .26-2.74l.12-.17.15-.2a1 1 0 0 0 .17-.85l-.04-.12-.58-1.46a1 1 0 0 1 .56-1.3Z""/>");
            builder.CloseElement();
        }
    }
}
