// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlServerLinkRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlServerLinkRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M9.25 6a.75.75 0 0 0 0 1.5h5.5a.75.75 0 0 0 0-1.5h-5.5ZM8.5 17.75c0-.41.34-.75.75-.75h2.08c-.18.47-.3.97-.32 1.5H9.25a.75.75 0 0 1-.75-.75Zm3.79-2.25a4.74 4.74 0 0 1 2.74-1.45.75.75 0 0 0-.28-.05h-5.5a.75.75 0 0 0 0 1.5h3.04ZM16.5 5v9H18V5a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v14a3 3 0 0 0 3 3h3.29c-.41-.43-.74-.94-.96-1.5H9A1.5 1.5 0 0 1 7.5 19V5c0-.83.67-1.5 1.5-1.5h6c.83 0 1.5.67 1.5 1.5ZM23 18.75A3.75 3.75 0 0 0 19.25 15h-.1a.75.75 0 0 0 .1 1.5h.15a2.25 2.25 0 0 1-.15 4.5l-.1.01a.75.75 0 0 0 .1 1.5v-.01h.2A3.75 3.75 0 0 0 23 18.74Zm-6.5-3a.75.75 0 0 0-.75-.75h-.2a3.75 3.75 0 0 0 .2 7.5h.1a.75.75 0 0 0-.1-1.5h-.15a2.25 2.25 0 0 1 .15-4.5h.1a.75.75 0 0 0 .65-.75Zm3.5 3a.75.75 0 0 0-.75-.75h-3.6a.75.75 0 0 0 .1 1.5h3.6a.75.75 0 0 0 .65-.75Z""/>");
            builder.CloseElement();
        }
    }
}
