// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlSportCricketBatRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlSportCricketBatRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M17.73 2.73a2.5 2.5 0 0 1 3.54 3.54l-3.6 3.6c-.43.42-.67 1-.67 1.6v.48c-.06.51-.29 1-.66 1.36l-8.02 8.03c-.88.88-2.3.88-3.18 0l-2.48-2.48a2.25 2.25 0 0 1 0-3.18l8.02-8.02c.43-.42 1-.66 1.6-.66h.25c.6 0 1.17-.24 1.6-.66l3.6-3.6ZM14.1 8.16c-.5.22-1.02.34-1.57.34h-.25c-.2 0-.4.08-.54.22l-8.02 8.02c-.29.3-.29.77 0 1.06l2.48 2.48c.29.29.77.29 1.06 0l8.02-8.03c.1-.1.18-.24.2-.38l.02-.15v-.26c0-.54.12-1.07.34-1.56L14.1 8.16Zm6.1-4.37a1 1 0 0 0-1.4 0l-3.48 3.47 1.42 1.42L20.2 5.2a1 1 0 0 0 0-1.42Z""/>");
            builder.CloseElement();
        }
    }
}
