// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.FluentUI
{
    /// <summary>
    /// FlTableCellAddRegular icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class FlTableCellAddRegular : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "currentColor");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<path d=""M10.75 3C9.51 3 8.5 4 8.5 5.25V8.5H5.25C4.01 8.5 3 9.5 3 10.75v2.5c0 1.24 1 2.25 2.25 2.25H8.5v3.25c0 1.24 1 2.25 2.25 2.25h1.27c-.3-.46-.53-.97-.7-1.5h-.57a.75.75 0 0 1-.75-.75V15.5h1.31c.18-.53.42-1.04.71-1.5H10v-4h4v2.02c.46-.3.97-.53 1.5-.7V10h3.25c.41 0 .75.34.75.75v.56c.53.18 1.04.42 1.5.71v-1.27c0-1.24-1-2.25-2.25-2.25H15.5V5.25c0-1.24-1-2.25-2.25-2.25h-2.5ZM14 8.5h-4V5.25c0-.41.34-.75.75-.75h2.5c.41 0 .75.34.75.75V8.5ZM8.5 10v4H5.25a.75.75 0 0 1-.75-.75v-2.5c0-.41.34-.75.75-.75H8.5ZM23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0Zm-5 .5v2.5a.5.5 0 1 1-1 0V18h-2.5a.5.5 0 0 1 0-1H17v-2.5a.5.5 0 1 1 1 0V17h2.5a.5.5 0 0 1 0 1H18Z""/>");
            builder.CloseElement();
        }
    }
}
