// <auto-generated/>
#nullable enable

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace EasyAppDev.Blazor.Icons.Lucide
{
    /// <summary>
    /// Construction icon from icon library.
    /// This component is fully embedded and trimmable.
    /// </summary>
    public sealed class Construction : ComponentBase
    {
        /// <summary>
        /// Accessible label for the icon. If not provided, icon will be marked as decorative (aria-hidden="true").
        /// </summary>
        [Parameter]
        public string? AriaLabel { get; set; }

        /// <summary>
        /// Additional HTML attributes to apply to the SVG element.
        /// </summary>
        [Parameter(CaptureUnmatchedValues = true)]
        public System.Collections.Generic.IReadOnlyDictionary<string, object>? AdditionalAttributes { get; set; }

        /// <inheritdoc/>
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenElement(0, "svg");
            builder.AddAttribute(1, "xmlns", "http://www.w3.org/2000/svg");
            builder.AddAttribute(2, "viewBox", "0 0 24 24");
            builder.AddAttribute(3, "width", "24");
            builder.AddAttribute(4, "height", "24");

                        builder.AddAttribute(5, "fill", "none");
            builder.AddAttribute(6, "stroke", "currentColor");
            builder.AddAttribute(7, "stroke-width", "2");
            builder.AddAttribute(8, "stroke-linecap", "round");
            builder.AddAttribute(9, "stroke-linejoin", "round");

            // Add user attributes AFTER defaults so they can override
            if (AdditionalAttributes != null)
            {
                builder.AddMultipleAttributes(10, AdditionalAttributes);
            }

            // Accessibility attributes
            if (!string.IsNullOrEmpty(AriaLabel))
            {
                builder.AddAttribute(11, "role", "img");
                builder.AddAttribute(12, "aria-label", AriaLabel);
            }
            else
            {
                builder.AddAttribute(11, "aria-hidden", "true");
            }

            // Inline SVG content
            builder.AddMarkupContent(13, @"<rect x=""2"" y=""6"" width=""20"" height=""8"" rx=""1"" /> <path d=""M17 14v7"" /> <path d=""M7 14v7"" /> <path d=""M17 3v3"" /> <path d=""M7 3v3"" /> <path d=""M10 14 2.3 6.3"" /> <path d=""m14 6 7.7 7.7"" /> <path d=""m8 6 8 8"" />");
            builder.CloseElement();
        }
    }
}
